

services:
  web-admin:
    build: 
      context: .
      dockerfile: dockerfile.dev
    env_file: .env.dev
    ports:
      - ${PORT:-8080}:8080
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:latest  # Using the MongoDB image
    env_file: .env.dev
    volumes:
      - ./mongodata:/data/db  # Persistent storage for MongoDB
    ports:
      - ${DB_PORT:-27017}:27017  # Expose MongoDB on port 27017 for local development
