# Use the official Golang image as the base image
FROM golang:1.22-alpine

# Set the working directory
WORKDIR /app

# Install Air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Run the application using Air for live reloading
CMD ["air", "-c", ".air.toml"]

